---
name: WWW-YouTube
version: 2006.0626
author:
  - 'Eric R. Meyers <ermeyers@adelphia.net>'
abstract: Interface to www.youtube.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 0
  Data::Dumper: 0
  Date::Format: 0
  Encode: 0
  File::Basename: 0
  FindBin: 0
  Frontier::Client: 0
  HTML::TreeBuilder: 0
  HTTP::Cookies: 0
  HTTP::Request::Common: 0
  IO::File: 0
  IO::Zlib: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  SQL::Statement: 0
  String::Approx: 0
  Term::ReadLine: 0
  Text::Wrap: 0
  XML::Dumper: 0
  XML::Parser: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
recommends:
  Test::Memory::Cycle: 0
  Test::Pod: 0
  Test::Taint: 0
  Test::Warn: 0
provides:
  WWW::YouTube:
    file: lib/WWW/YouTube.pm
    version: 2006.0626
  WWW::YouTube::Com:
    file: lib/WWW/YouTube/Com.pm
    version: 2006.0626
  WWW::YouTube::HTML:
    file: lib/WWW/YouTube/HTML.pm
    version: 2006.0626
  WWW::YouTube::HTML::API:
    file: lib/WWW/YouTube/HTML/API.pm
    version: 2006.0626
  WWW::YouTube::ML:
    file: lib/WWW/YouTube/ML.pm
    version: 2006.0626
  WWW::YouTube::ML::API:
    file: lib/WWW/YouTube/ML/API.pm
    version: 2006.0626
  WWW::YouTube::XML:
    file: lib/WWW/YouTube/XML.pm
    version: 2006.0626
  WWW::YouTube::XML::API:
    file: lib/WWW/YouTube/XML/API.pm
    version: 2006.0626
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
